# Generated by Django 3.2.25 on 2024-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_delete_store'),
        ('store', '0002_auto_20240529_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='books',
            field=models.ManyToManyField(related_name='books', through='store.Inventory', to='book.Book'),
        ),
    ]
