# Generated by Django 3.2.25 on 2024-05-29 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory', to='store.store'),
        ),
    ]
