# Generated by Django 3.2.25 on 2024-05-30 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20240530_0703'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_inventory_unique_book_per_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_quantity', to='book.book')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_quantity', to='store.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quantity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='customers',
            field=models.ManyToManyField(related_name='stores', through='store.Quantity', to=settings.AUTH_USER_MODEL),
        ),
    ]
