# Generated by Django 3.2.25 on 2024-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20240530_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='revenue',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
