# Generated by Django 3.2.25 on 2024-06-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='revenue',
        ),
    ]
