# Generated by Django 3.2.25 on 2024-06-18 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0008_orderitem_out_for_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('payment_method', models.CharField(choices=[('UPI', 'Upi Payment'), ('COD', 'Cash on Delivery'), ('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card')], max_length=6)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('CNF', 'Confirmed'), ('FAIL', 'Failed')], max_length=7)),
                ('transaction_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
