# Generated by Django 3.2.25 on 2024-05-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
    ]
