# Generated by Django 3.2.25 on 2024-05-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_author_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
