# Generated by Django 3.2.25 on 2024-06-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_message',
            field=models.TextField(default='Order Created Successfully'),
        ),
    ]
