# Generated by Django 3.2.25 on 2024-06-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitem_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='out_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
